version: '3'

services:
  zulip:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "9991:9991"
    volumes:
      - ".:/srv/zulip"
    command: /srv/zulip/tools/start-docker-compose-dev
    depends_on:
      - memcached
      - rabbitmq
      - redis

  memcached:
   image: memcached
   restart: always

  rabbitmq:
    image: rabbitmq:3.5.5
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "zulip"
      RABBITMQ_DEFAULT_PASS: "f62c674ef5edd465027a0763555c2a9849f751a472e55b4a0000cb8350b2787f"

  redis:
    image: redis
