# Generated by Django 4.2.2 on 2023-07-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0464_remove_realmplayground_url_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedattachment",
            name="tus_file_id",
            field=models.CharField(db_index=True, max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="attachment",
            name="tus_file_id",
            field=models.CharField(db_index=True, max_length=60, null=True, unique=True),
        ),
    ]
