# Generated by Django 5.0.6 on 2024-07-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0555_alter_onboardingstep_onboarding_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="web_left_sidebar_unreads_count_summary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="web_left_sidebar_unreads_count_summary",
            field=models.BooleanField(default=False),
        ),
    ]
