# Generated by Django 5.0.7 on 2024-08-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0575_alter_directmessagegroup_group_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
