# Generated by Django 5.0.8 on 2024-08-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0577_merge_20240829_0153"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiuseinvite",
            name="user_groups",
            field=models.ManyToManyField(to="zerver.namedusergroup"),
        ),
        migrations.AddField(
            model_name="preregistrationuser",
            name="user_groups",
            field=models.ManyToManyField(to="zerver.namedusergroup"),
        ),
    ]
