name: Update Zulip-openapi

on: [push]

defaults:
  run:
    shell: bash

jobs:
  generate-api-docs:
    runs-on: ubuntu-latest
    name: Ubuntu 18.04 Bionic (Python 3.6, backend + frontend)

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.17.3"
      - run: npm install @openapitools/openapi-generator-cli@2.3.7
      - name: creates output
        run: bash ./tools/ci/openapi-generator
      - name: Push documentation to zulip-openapi
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "openapi-output"
          destination-github-username: "MSurfer20"
          destination-repository-name: "test2"
          user-email: suyash.mathur@research.iiit.ac.in
          commit-message: Update docs from ORIGIN_COMMIT
          target-branch: main
